---
- hosts: all
  name: common configuration
  roles:
    - role: timezone
    - role: authorized_keys
    - role: apt-upgrade
    - role: packages
    - role: dotfiles-chezmoi

- hosts: nameserver
  name: nameserver
  roles:
    - role: bind-secondary
