---
- hosts: all
  name: common configuration
  roles:
    - role: timezone
    - role: authorized_keys
    - role: apt-upgrade
    - role: dotfiles-chezmoi


- hosts: ubuntu
  name: ubuntu packae install
  roles:
    - role: packages
      vars:
        install_packages: "{{ packages }}"

- hosts: emacs
  name: install emacs
  roles:
    - role: emacs

- hosts: docker
  name: install docker
  roles:
    - role: docker
