---
- hosts: all
  name: common configuration
  roles:
    - role: timezone
    - role: authorized_keys
    - role: apt-upgrade
    - role: dotfiles-chezmoi


- hosts: noble
  name: ubuntu noble configuration
  roles:
    - role: packages
      vars:
        install_packages: "{{ packages }}"

- hosts: emacs
  name: install emacs
  roles:
    - role: emacs
