---
- hosts: all
  name: common configuration
  roles:
    - role: timezone
    - role: authorized_keys_work
    - role: apt-upgrade
    - role: dotfiles-chezmoi


- hosts: noble
  name: ubuntu noble configuration
  roles:
    - role: packages
      vars:
        install_packages: "{{ packages }}"

- hosts: emacs28
  name: install emacs28
  roles:
    - role: emacs28
